/* Exports the game world exactly as the browser builds it into core/mapdata.js, so the
   multiplayer server collides players and bullets against the same geometry the players see.
   - tris:      every triangle bullets can hit (all W.ray meshes), world space, mm precision
   - ds:        1 = that triangle is hit from both sides (DoubleSide material), 0 = front face only,
                exactly like Three.js raycasting
   - colliders: the movement boxes (W.colliders)      - ramps: W.ramps
   - nav:       the walkable grid points of the town (spawn candidates)
   Run after changing the map:  node tools/export-map.js   (needs playwright)
   test/browser.test.js fails if the file no longer matches the page. */
'use strict';
const fs = require('fs'), path = require('path');
// one map (id) as the page builds it; the page is switched to that map for the dump
async function dumpWorld(page, id) {
  return page.evaluate((id) => {
    const prev = __SD.WORLD_ID; if (id) __SD.setWorld(id);
    const W = __SD.W, v = new THREE.Vector3(), out = [], ds = [];
    const r3 = x => Math.round(x * 1000) / 1000;
    for (const m of W.ray) {
      m.updateMatrixWorld(true);
      const g = m.geometry, pos = g.attributes.position, idx = g.index;
      const n = idx ? idx.count : pos.count;
      const two = [].concat(m.material).some(mt => mt && mt.side === THREE.DoubleSide) ? 1 : 0;
      for (let i = 0; i < n / 3; i++) ds.push(two);
      for (let i = 0; i < n; i++) { const k = idx ? idx.getX(i) : i; v.fromBufferAttribute(pos, k).applyMatrix4(m.matrixWorld); out.push(r3(v.x), r3(v.y), r3(v.z)); }
    }
    const rb = o => { const c = {}; for (const k in o) c[k] = typeof o[k] === 'number' ? r3(o[k]) : o[k]; return c; };
    const nav = (id && __SD.WORLDS[id] ? __SD.WORLDS[id].nav : __SD.NAV).map(n => [n.x, n.z]);
    const res = { tris: out, ds, colliders: W.colliders.map(rb), ramps: (W.ramps || []).map(rb), nav };
    __SD.setWorld(prev); return res;
  }, id || null);
}
// maps: { pueblo: dump, arena: dump }. The module keeps the town at the top level (older code)
// and every map under .maps
function toModule(maps) {
  const pack = d => ({ tris: d.tris, ds: d.ds, colliders: d.colliders, ramps: d.ramps, nav: d.nav });
  const all = {}; for (const k in maps) all[k] = pack(maps[k]);
  return '/* GENERATED by tools/export-map.js from the page world. Do not edit by hand. */\n' +
    "(function (root) {\n'use strict';\nconst MAPS = " + JSON.stringify(all) + ";\n" +
    "const SD_MAP = Object.assign({ version: 2, maps: MAPS }, MAPS.pueblo);\n" +
    "if (typeof module !== 'undefined' && module.exports) module.exports = SD_MAP; else root.SD_MAP = SD_MAP;\n})(typeof window !== 'undefined' ? window : globalThis);\n";
}
async function main() {
  const { chromium } = require('playwright');
  const S = await require('./static-server.js').start();
  const b = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const p = await b.newPage(); await p.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
  await p.goto(S.url); await p.waitForFunction(() => window.__SD && __SD.W && __SD.W.ray.length > 0);
  const ids = await p.evaluate(() => Object.keys(__SD.WORLDS));
  const maps = {}; for (const id of ids) maps[id] = await dumpWorld(p, id);
  await b.close(); S.close();
  fs.writeFileSync(path.join(__dirname, '..', 'core', 'mapdata.js'), toModule(maps));
  for (const id of ids) { const d = maps[id]; console.log('core/mapdata.js [' + id + ']: ' + d.tris.length / 9 + ' triángulos, ' + d.colliders.length + ' cajas, ' + d.ramps.length + ' rampas, ' + d.nav.length + ' puntos'); }
}
module.exports = { dumpWorld, toModule };
if (require.main === module) main().catch(e => { console.error(e); process.exit(1); });
